function greeter_clear_config -d "clear greeter configuration"
  set -eU greeter_logo_path
  set -eU greeter_line_color
  set -eU greeter_line
  set -eU greeter_newline
  set -eU greeter_order
  set -eU greeter_title_space
  set -eU greeter_title_user_color
  set -eU greeter_title_user
  set -eU greeter_title_separator_color
  set -eU greeter_title_separator
  set -eU greeter_title_host_color
  set -eU greeter_title_host
  set -eU greeter_os_space
  set -eU greeter_os_icon_color
  set -eU greeter_os_icon
  set -eU greeter_os_text_color
  set -eU greeter_os_text
  set -eU greeter_os_text_suffix
  set -eU greeter_os_separator_color
  set -eU greeter_os_separator
  set -eU greeter_os_value_color
  set -eU greeter_os_value
  set -eU greeter_host_space
  set -eU greeter_host_icon_color
  set -eU greeter_host_icon
  set -eU greeter_host_text_color
  set -eU greeter_host_text
  set -eU greeter_host_text_suffix
  set -eU greeter_host_separator_color
  set -eU greeter_host_separator
  set -eU greeter_host_value_color
  set -eU greeter_host_value
  set -eU greeter_kernel_space
  set -eU greeter_kernel_icon_color
  set -eU greeter_kernel_icon
  set -eU greeter_kernel_text_color
  set -eU greeter_kernel_text
  set -eU greeter_kernel_text_suffix
  set -eU greeter_kernel_separator_color
  set -eU greeter_kernel_separator
  set -eU greeter_kernel_value_color
  set -eU greeter_kernel_value
  set -eU greeter_uptime_space
  set -eU greeter_uptime_icon_color
  set -eU greeter_uptime_icon
  set -eU greeter_uptime_text_color
  set -eU greeter_uptime_text
  set -eU greeter_uptime_text_suffix
  set -eU greeter_uptime_separator_color
  set -eU greeter_uptime_separator
  set -eU greeter_uptime_value_color
  set -eU greeter_uptime_value
  set -eU greeter_shell_space
  set -eU greeter_shell_icon_color
  set -eU greeter_shell_icon
  set -eU greeter_shell_text_color
  set -eU greeter_shell_text
  set -eU greeter_shell_text_suffix
  set -eU greeter_shell_separator_color
  set -eU greeter_shell_separator
  set -eU greeter_shell_value_color
  set -eU greeter_shell_value
  set -eU greeter_terminal_space
  set -eU greeter_terminal_icon_color
  set -eU greeter_terminal_icon
  set -eU greeter_terminal_text_color
  set -eU greeter_terminal_text
  set -eU greeter_terminal_text_suffix
  set -eU greeter_terminal_separator_color
  set -eU greeter_terminal_separator
  set -eU greeter_terminal_value_color
  set -eU greeter_terminal_value
  set -eU greeter_cpu_space
  set -eU greeter_cpu_icon_color
  set -eU greeter_cpu_icon
  set -eU greeter_cpu_text_color
  set -eU greeter_cpu_text
  set -eU greeter_cpu_text_suffix
  set -eU greeter_cpu_separator_color
  set -eU greeter_cpu_separator
  set -eU greeter_cpu_value_color
  set -eU greeter_cpu_value
  set -eU greeter_gpu_space
  set -eU greeter_gpu_icon_color
  set -eU greeter_gpu_icon
  set -eU greeter_gpu_text_color
  set -eU greeter_gpu_text
  set -eU greeter_gpu_text_suffix
  set -eU greeter_gpu_separator_color
  set -eU greeter_gpu_separator
  set -eU greeter_gpu_value_color
  set -eU greeter_gpu_value
  set -eU greeter_memory_space
  set -eU greeter_memory_icon_color
  set -eU greeter_memory_icon
  set -eU greeter_memory_text_color
  set -eU greeter_memory_text
  set -eU greeter_memory_text_suffix
  set -eU greeter_memory_separator_color
  set -eU greeter_memory_separator
  set -eU greeter_memory_value_color

  true
end
